In [1]:
# Intro. Exp. Physics II HW5, Gabriel Bridges
# Problem 4.2
# GLB300@nyu.edu

import numpy as np

In [2]:
a = np.array([1, 3, 5, 7])
b = np.array([8, 7, 5, 4])
c = np.array([0, 9,-6,-8])

In [3]:
d = zip(a, b, c)
print d

[(1, 8, 0), (3, 7, 9), (5, 5, -6), (7, 4, -8)]


In [4]:
e = np.array(d)
print e

[[ 1  8  0]
 [ 3  7  9]
 [ 5  5 -6]
 [ 7  4 -8]]


In [5]:
print e[3, 2]
print d[3][2]

-8
-8
